---
- name: build html website
  hosts: localhost
  connection: localhost
  gather_facts: False
  
  vars:
    path: "/Users/jw/Documents/GitHub/julianwe.github.io"
  
  vars_prompt:
    - name: pw
      prompt: Enter the Docker password
  
  tasks:

    - name: convert README to HTML
      shell: | 
        cd {{ path }}
        for folder in projects/*; do pandoc -f markdown -t html5 $folder/README.md > projects/${folder#*/}/${folder#*/}.html;  
        done;
        ls {{ path }}/projects
      register: folder
  
    - name: set project, URLs & directorys facts
      set_fact:
        name: "{{ item | trim ('/')}}"
        file_path: "{{ path }}/projects/{{ item }}/{{ item | trim ('/')}}.html"
        projects_templatej2:  "{{ path }}/projects/ansible/projects_template.j2"
        projectsj2: "{{ path }}/projects/ansible/projects.j2"
        projectj2: "{{ path }}/projects/ansible/project.j2"
        url: "https://julianwe.github.io/projects/{{ item }}/{{ item | trim('/')}}.html"
        identifier: "{{ index }}"
      loop: "{{ folder.stdout_lines }}"
      loop_control:
        index_var: index
      register: facts
  
    - name: set html content facts
      set_fact:
        html: "{{ lookup('file', item.ansible_facts.file_path) }}"
        file_path: "{{ item.ansible_facts.file_path }}"
        url: "{{ item.ansible_facts.url }}"
        identifier: "{{ item.ansible_facts.identifier }}"
        name: "{{ item.ansible_facts.name }}"
      loop: "{{ facts.results }}"
      register: html_files

    - name: create project HTML sites
      template:
        src: "{{ projects_templatej2 }}"
        dest: "{{ item.ansible_facts.file_path }}"
      delegate_to: localhost
      when: item.ansible_facts.name != "projects"
      loop: "{{ html_files.results }}"
  
    - name: set fact
      set_fact:
        projects_html: "{{ item.ansible_facts.html }}"
      when: item.ansible_facts.name == "projects"
      loop: "{{ html_files.results }}"
  
    - name: read the csv file
      read_csv:
        path: "/Users/jw/Documents/GitHub/julianwe.github.io/projects/projects/projects.csv"
        delimiter: ','
      register: projects_csv

  
    # - name: create project site
    #   template:
    #     src: "{{ projectj2 }}"
    #     dest: "{{ path }}/projects-test.html"
    #   delegate_to: localhost
    - name: docs
      docker_container:


    - name: Stop a container
      docker_container:
        name: docker-repo:webapp
        state: stopped
      when: state == started
  
    - name: Log into private registry and force re-authorization
      docker_login:
        username: "victorynox0815"
        password: "{{ pw }}"
        reauthorize: true
      register: login
  
    - name: Build an image and push
      docker_image:
        build:
          path: "{{ path }}" 
        name: victorynox0815/docker-repo:webapp
        tag: v2
        force_source: yes
        push: yes
        source: build
      delegate_to: localhost
  
    - name: Start a container
      docker_container:
        name: webapp
        state: started
  
    - name: Deploy Website on IPFS
      command: ipfs add -r {{ path }}
...
