name: Deploy GitHub Pages

on:
  push:
    branches: [ main ] # Change to the branch you want to use for deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Build and Deploy
      uses: actions/deploy-pages@v1
