all:
  hosts:
    node1:
      ansible_host: 10.0.10.11
      ip: 10.0.10.11
      access_ip: 10.0.10.11
    node2:
      ansible_host: 10.0.10.12
      ip: 10.0.10.12
      access_ip: 10.0.10.12
    node3:
      ansible_host: 10.0.10.13
      ip: 10.0.10.13
      access_ip: 10.0.10.13
    node4:
      ansible_host: 10.0.10.14
      ip: 10.0.10.14
      access_ip: 10.0.10.14
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
