all:
  hosts:
    node1:
      ansible_host: 172.20.0.21
      ip: 172.20.0.21
      access_ip: 172.20.0.21
    node2:
      ansible_host: 172.20.0.22
      ip: 172.20.0.22
      access_ip: 172.20.0.22
    node3:
      ansible_host: 172.20.0.23
      ip: 172.20.0.23
      access_ip: 172.20.0.23
    node4:
      ansible_host: 172.20.0.24
      ip: 172.20.0.24
      access_ip: 172.20.0.24
    node5:
      ansible_host: 172.20.0.25
      ip: 172.20.0.25
      access_ip: 172.20.0.25
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}