# Create gcp compute instance using Ansible Playbooks & Roles
# Author: Julian Wendland
---
- hosts: gcp_test
  tasks:

    - name: Include variables from a file
      include_vars:
        file: "../roles/gcp/vars/main.yml"
      register: vars

    - name: Include the gcp role
      include_role:
        name: roles/gcp
