---
version: "2.0"

services:
  app:
    image: declab/sentinel_dvpn:0.7.1.1
    env:
      - "MNEMONIC_BASE64=b3pvbmUgY29taWMgY2FzdWFsIGVuZGxlc3MgcHVuY2ggaGFwcHkgYnVyc3QgcGhvdG8gaW5kdXN0cnkgZGlzbWlzcyBjbGVhbiBjb3JuIGNhc3RsZSBib3JkZXIgYmFjaGVsb3IgdmFyaW91cyBtb3NxdWl0byBkYW1hZ2Ugb3duIGFzcGVjdCBzaGVyaWZmIGZvY3VzIGFuc3dlciBtYWNoaW5l" # Mnemonic phrase encrypted with BASE64.
      - "MONIKER=dVPN on Akash Network v2RAY" # Your dVPN node name.
      - "REMOTE_PORT=8585" # Remote port for are connection sentinel client service.
      - "LISTEN_PORT=3333" # v2RAY listen port
      - "IPV4_ADDRESS=" # Node static IP address ( of leases section )
      - "RPC_ADDRESS=https://rpc.sentinel.co:443"
      
      - "GIGABYTE_PRICES=52573ibc/31FEE1A2A9F9C01113F90BD0BBCCE8FD6BBB8585FAF109A2101827DD1D5B95B8,9204ibc/A8C2D23A1E6F95DA4E48BA349667E322BD7A6C996D8A4AAE8BA72E190F3D1477,1180852ibc/B1C0DDB14F25279A2026BC8794E12B259F8BDA546A3C5132CCAEE4431CE36783,122740ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518,15342624udvpn"
         # ^^Set the cost per 1 Gb of active traffic passed through your node.^^
         
      - "HOURLY_PRICES=18480ibc/31FEE1A2A9F9C01113F90BD0BBCCE8FD6BBB8585FAF109A2101827DD1D5B95B8,770ibc/A8C2D23A1E6F95DA4E48BA349667E322BD7A6C996D8A4AAE8BA72E190F3D1477,1871892ibc/B1C0DDB14F25279A2026BC8794E12B259F8BDA546A3C5132CCAEE4431CE36783,18897ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518,10000000udvpn" # Set the cost per 1 hour of traffic passed through your node.
         
    expose:
      - port: 8585 # REMOTE_URL_PORT
        as: 8585
        to:
          - global: true
      - port: 3333 # LISTEN_PORT 
        as: 3333
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 3Gi         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 100000
deployment:
  app:
    akash:
      profile: app
      count: 1 
