
---
- name: gcloud compute instances create
  shell: | 
    gcloud compute instances create {{ vars.vms.vm.name }} \
        --project={{ vars.vms.vm.project }} \
        --zone={{ vars.vms.vm.zone }} \
        --machine-type={{ vars.vms.vm.size }} \
        --network-interface=network-tier={{ vars.vms.vm.network_tier }},stack-type={{ vars.vms.vm.stack_type }},subnet={{ vars.vms.vm.subnet }} \
        --metadata=ssh-keys={{ vars.vms.vm.ssh }} \
        --maintenance-policy={{ vars.vms.vm.maintenance_policy }} \
        --provisioning-model={{ vars.vms.vm.provisioning_model }} \
        --service-account={{ vars.vms.vm.sa }} \
        --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/trace.append \
        --create-disk=auto-delete=yes,boot=yes,device-name=ansible-1,disk-resource-policy=projects/akash-456617/regions/us-central1/resourcePolicies/default-schedule-1,image=projects/ubuntu-os-cloud/global/images/ubuntu-2404-noble-amd64-v20250409,mode=rw,size=10,type=pd-standard \
        --no-shielded-secure-boot \
        --shielded-vtpm \
        --shielded-integrity-monitoring \
        --labels=goog-ec-src=vm_add-gcloud \
        --reservation-affinity=any \
        --enable-nested-virtualization
  register: vm

- name: set fact
  set_fact:
    IPs:  "{{ vm.stdout_lines | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

- name: External IP
  debug:
    msg: "{{ IPs.1 }}"
...