
---
- name: gcloud compute instances create
  shell: | 
    gcloud compute instances create ansible \
        --project=akash-456617 \
        --zone=us-central1-c \
        --machine-type=e2-standard-2 \
        --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
        --metadata=enable-osconfig=TRUE,ssh-keys=jw:ssh-ed25519\ \
    AAAAC3NzaC1lZDI1NTE5AAAAIKTNqCzRZVoWV5hbr4yj\+mnV0ckEBfr68LC3BqZd3JsD\ jw \
        --maintenance-policy=MIGRATE \
        --provisioning-model=STANDARD \
        --service-account=513538345283-compute@developer.gserviceaccount.com \
        --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/trace.append \
        --create-disk=auto-delete=yes,boot=yes,device-name=ansible,disk-resource-policy=projects/akash-456617/regions/us-central1/resourcePolicies/default-schedule-1,image=projects/debian-cloud/global/images/debian-12-bookworm-v20250513,mode=rw,size=100,type=pd-balanced \
        --create-disk=device-name=sdb,disk-resource-policy=projects/akash-456617/regions/us-central1/resourcePolicies/default-schedule-1,mode=rw,name=sdb,size=100,type=pd-balanced \
        --no-shielded-secure-boot \
        --shielded-vtpm \
        --shielded-integrity-monitoring \
        --labels=goog-ops-agent-policy=v2-x86-template-1-4-0,goog-ec-src=vm_add-gcloud \
        --reservation-affinity=any \
        --project=akash-456617 \
        --zone=us-central1-c \
        --enable-nested-virtualization
  register: vm

- name: set fact
  set_fact:
    IPs:  "{{ vm.stdout_lines | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

- name: External IP
  debug:
    msg: "{{ IPs.1 }}"
...