- name: Create GCP instance
  gcp_compute_instance:
    name: ansible
    machine_type: t2d-standard-1
    disks:
      - boot:
          auto_delete: true
          initialize_params:
            source_image: projects/debian-cloud/global/images/debian-9-drawfork-v20180627
    network_interface:
      network: default
      access_config: {}
    zone: us-central1-a
    auth_kind: serviceaccount
    project: my-project-id
    service_account_file: /path/to/service-account-file.json

- name: Deploy Docker container
  docker_container:
    name: ubuntu
    image: my-docker-image:latest
    state: started
    restart_policy: always
    pull: yes
  delegate_to: localhost

