---
- name: convert markdown readme to html
  shell: | 
    cd {{ vars.paths.path }}
    for folder in roles/*; do pandoc -f markdown -t html5 $folder/files/README.md > roles/${folder#*/}/files/${folder#*/}.html;  
    done;
    ls {{ vars.paths.path }}/roles
  register: folder

- name: set blogpost & directory facts
  no_log: true
  set_fact:
    name: "{{ item | trim ('/')}}"
    file_path: "{{ vars.paths.path }}/roles/{{ item }}/files/{{ item | trim ('/')}}.html"
  loop: "{{ folder.stdout_lines }}"
  loop_control:
    index_var: index
  register: facts

- name: set html blogpost content facts
  no_log: true
  set_fact:
    html: "{{ lookup('file', item.ansible_facts.file_path) }}"
    file_path: "{{ item.ansible_facts.file_path }}"
    name: "{{ item.ansible_facts.name }}"
  loop: "{{ facts.results }}"
  register: html_files

- name: create blogpost html pages
  no_log: true
  template:
    src: "{{ vars.paths.blogpost }}"
    dest: "{{ item.ansible_facts.file_path }}"
  delegate_to: localhost
  loop: "{{ html_files.results }}"

- name: create index.html file
  template:
    src: "{{ vars.paths.index_template }}"
    dest: "{{ vars.paths.index_file }}"
  delegate_to: localhost

- name: copy html blogposts to blog folder
  shell:
    cmd: "cp {{ item.ansible_facts.file_path }} {{ vars.paths.blog_folder }}"
  loop: "{{ facts.results }}"

- name: copy index.html to repository
  shell:
    cmd: "cp {{ vars.paths.index_file }} {{ vars.paths.repository }}"
...