---
# - name: install kubespray
#   shell: | 
#     cd ~
#     git clone -b v2.26.0 --depth=1 https://github.com/kubernetes-sigs/kubespray.git
#     cd kubespray
#     apt-get update ; apt-get install -y python3-pip virtualenv -y
#     cd ~/kubespray
#     virtualenv --python=python3 venv
#     source venv/bin/activate 
#     pip3 install -r requirements.txt
#   register: kubespray 

- name: generate ssh key
  shell: | 
    ssh-keygen -t rsa -C $(hostname) -f "$HOME/.ssh/id_rsa" -P "" ; cat ~/.ssh/id_rsa.pub
  register: ssh_key

- name: generate inventory
  shell: | 
    cd ~/kubespray
    cp -rfp inventory/sample inventory/akash
    declare -a IPS=(10.0.10.11 10.0.10.12 10.0.10.13 10.0.10.14)
    CONFIG_FILE=inventory/akash/hosts.yaml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
  register: inventory

- name: systemctl start kubelet & kubectl
  shell: | 
    systemctl start containerd
    systemctl enable containerd
    systemctl start kubelet
    systemctl enable kubelet
    journalctl -u kubelet -f
    kubectl get pods -A -o wide 
  register: kubectl
...
