---
- name: install kubespray
  shell: | 
    cd ~
    git clone -b v2.26.0 --depth=1 https://github.com/kubernetes-sigs/kubespray.git
    cd ~/kubespray
    virtualenv --python=python3 venv
    source venv/bin/activate 
    pip3 install -r requirements.txt
  register: kubespray 

- name: generate ssh key
  shell: | 
    ssh-keygen -t rsa -C $(hostname) -f "$HOME/.ssh/id_rsa" -P "" ; cat ~/.ssh/id_rsa.pub 
  register: ssh_key

- name: generate ssh key
  shell: | 
    git clone https://github.com/akash-network/provider-playbooks.git
    cd provider-playbooks
    ./scripts/setup_provider.sh
  register: ssh_key

- name: systemctl start kubelet & kubectl
  shell: | 
    systemctl start containerd
    systemctl enable containerd
    systemctl start kubelet
    systemctl enable kubelet
    kubectl get pods -A -o wide  
  register: systemctl
...
